import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import type { ApiResponseType, RpcApis } from "@/apis";
import { createApiProxy } from "@/trpc/client";

const inter = Inter({ subsets: ["latin"] });

type User = ApiResponseType<"query", "userById">;
type Application = ApiResponseType<"mutation", "getAllMyApps">[0];

const apis = createApiProxy<RpcApis>();

export default function Home() {
  const [user, setUser] = useState<User>();
  useEffect(() => {
    (async () => {
      const res = await apis.query.userById({ userId: 12 });
      setUser(res);
    })();
  }, []);

  const [apps, setApps] = useState<Application[]>([]);
  useEffect(() => {
    (async () => {
      const res = await apis.mutation.getAllMyApps();
      setApps(res);
    })();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1> Users </h1>
          <pre>
            <code>
              {JSON.stringify(user)}
            </code>
          </pre>
        </div>
        <div>
          <h1> Applications </h1>
          <pre>
            <code>
              {JSON.stringify(apps)}
            </code>
          </pre>
        </div>
      </main>
    </>
  );
}
